"""migration_2

Revision ID: 90c82df983ff
Revises: d59310cbe4a8
Create Date: 2022-10-13 19:58:01.880350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c82df983ff'
down_revision = 'd59310cbe4a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
